name: Redis Service Example

on: push

jobs:
  talk-to-redis:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
        - 6379/tcp

    steps:
    - uses: actions/checkout@v1

    - run: npm ci
      working-directory: ./redis

    - run: node index.js
      working-directory: ./redis
      env:
        REDIS_HOST: localhost
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}